# Generated by Django 3.2.3 on 2021-10-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211019_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
    ]
