# Generated by Django 3.2.3 on 2021-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured', models.BooleanField()),
                ('instock', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Elec', 'Electronics'), ('MCol', "Men's Fashion"), ('FCol', "Women's Fashion")], max_length=4)),
                ('product_img', models.ImageField(default='default.jpg', upload_to='image/')),
            ],
        ),
    ]
