# Generated by Django 3.2.3 on 2021-10-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='Categories',
        ),
    ]
