# Generated by Django 3.2.3 on 2021-10-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_specific_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specific_cat',
        ),
    ]
