# Generated by Django 3.2.3 on 2021-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
        ),
    ]
