# Generated by Django 3.2.3 on 2021-10-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_specific_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specific_cat',
        ),
        migrations.AddField(
            model_name='product',
            name='specific_cat',
            field=models.ManyToManyField(blank=True, null=True, to='products.Categories'),
        ),
    ]
