# Generated by Django 3.2.3 on 2021-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211019_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Elec', 'Electronics'), ('MCol', "Men's Fashion"), ('FCol', "Women's Fashion")], max_length=4),
        ),
    ]
