# Generated by Django 3.2.3 on 2021-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211019_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specific_cat',
            field=models.ManyToManyField(blank=True, to='products.Categories'),
        ),
    ]
