# Generated by Django 3.2.3 on 2021-10-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211019_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specific_cat',
            new_name='category',
        ),
    ]
